# Generated by Django 4.0.5 on 2022-09-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('account_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
